In [1]:
#         THEORY QUESTIONS:


# Q1:- Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's
              #capabilities for numerical operations?

# NumPy (Numerical Python) is a fundamental library in Python for scientific computing and data analysis.
# It provides support for multi-dimensional arrays and matrices, along with a collection of mathematical functions to 
        #operate on these arrays.

# Here are some key advantages & ways for numerical operations:----
   
    
# 1.  Array Operations:-
#(a) Multi-Dimensional Arrays: Numpy introduces the ndarray object, a powerful n-dimensional array that allows for efficient storage and manipulation of numerical 
                                #data. Unlike Python's built-in lists, NumPy arrays are more compact and provide better performance for numerical computations.
#(b) Element-Wise Operations: it concise and compute, Operations on arrays are automatically vectorized, meaning that operations are performed on entire arrays 
                              #without the need for explicit loops, which significantly speeds up computations.

    
# 2. Performance:-
#(a) Speed: its operations much faster than Python loops. This is because the heavy lifting is done in lower-level languages, 
            #and Python merely acts as a high-level interface.
#(b) Memory Efficiency: NumPy arrays use less memory compared to Python lists. They store data in contiguous blocks of memory and use a fixed-size data type,
                        #which makes them more memory-efficient and faster to access.
    
    
# 3. Mathematical Functions:-
#(a) Comprehensive Library: NumPy provides a vast array of mathematical functions and operations, including linear algebra, statistical operations,
                            #These functions are optimized for performance and are essential for many scientific computing tasks.
#(b) Broadcasting: it allows operations on arrays of different shapes. This feature simplifies code and can lead to significant performance improvements
                    #by eliminating the need for explicit looping or replication of data.


# 4. Convenience:-
#(a) Ease of Use: NumPy provides a high-level API for handling numerical data, which simplifies code and improves readability. Operations that would 
                  #require complex looping and manual calculations in native Python can be achieved with a few lines of code using NumPy functions.
#(b) Array Manipulation: NumPy offers powerful tools for reshaping, slicing, and manipulating arrays, which are crucial for preparing and analyzing data
                         #efficiently.
    
    
#   SUMMARY:-

# Numpy significantly enhances Python’s capabilities for numerical operations by providing efficient array handling, fast computation, extensive mathematical 
#functions, & seamless integration with other scientific libraries, its performance and ease of use make it a cornerstone of scientific computing & data analysis 
#in Python.

In [2]:
#Q2:-    Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


#np.mean()  used for simple arithmetic mean of an array, does't support weights, only use for general mean calculations
#SYNTAX >>  np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

#EXAMPLE:-
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr) 
mean_value                   # Output: 3.0

np.float64(3.0)

In [3]:
#np.average() computes the weighted average if weights are provided 
#SYMTAX >>  np.average(a, axis=None, weights=None, returned=False)
 
#EXAMPLE:-
import numpy as np

values = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 1, 1, 1])
weighted_avg = np.average(values, weights=weights)  

weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
weighted_avg = np.average(values, weights=weights) 
weighted_avg                                       


np.float64(3.2)

In [4]:
#SUMMARY:-
# np.mean() used for general mean calculations, while np.average() provides additional functionality for computing weighted means.


In [5]:
#Q3:-  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays?

# we can reversing a numpy array with the 'slicing' method in both 1D and 2D arrays along with different axes.
# Here's an example:-

# 1D numpy array:-

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
reversed_arr=arr[::-1]

print('original_arr', arr)
print('reverced_arr', reversed_arr)     #OUTPUT>> [9 8 7 6 5 4 3 2 1]


original_arr [1 2 3 4 5 6 7 8 9]
reverced_arr [9 8 7 6 5 4 3 2 1]


In [6]:
#2D numpy array along y-axis(rows):-

import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
reversed_arr=arr[::-1,:]                 # for reverse the rows

print('reversed_rows:---', reversed_arr)

reversed_rows:--- [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [7]:
#2D numpy array along x-axis(column):-
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
reversed_arr=arr[:,::-1]                 # for reversing the column in 2D numpy array

print('reversed_column:---', reversed_arr)
       

reversed_column:--- [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [8]:
#2D numpy array along both axis:-
import numpy as np
np.array([[1,2,3],
         [4,5,6],
         [7,8,9]])
reversed_arr=arr[::-1, ::-1]            # for reversing the both axis simultaneously(rows & columns)

print('reversed_arr:--', reversed_arr)


reversed_arr:-- [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [9]:
#Summary:-

#1D Arrays: Use slicing [::-1] to reverse the array.
#2D Arrays:
#         Reverse Rows: Use slicing [::-1, :].
#         Reverse Columns: Use slicing [:, ::-1].
#         Reverse Both Axes: Use slicing [::-1, ::-1].

# These slicing techniques are efficient and leverage numpy powerful indexing capabilities to manipulate array dimensions.

In [10]:
#Q4:- How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

# To determine the data type of elements in a NumPy array, you use the .dtype attribute of the array. 
# This attribute provides information about the type of data stored in the array.

#EXAMPLE:-

import numpy as np
arr_int=np.array([1,2,3,4,5])
arr_float=np.array([1.2,3.5])
arr_str=np.array(['saumya','kesarwani'])
arr_bool=np.array(['True', 'False'])
arr_complex=np.array([3+5j])

print('arr_a:--', arr_int.dtype)
print('arr_b:--', arr_float.dtype)
print('arr_c:--', arr_str.dtype)
print('arr_d:--', arr_bool.dtype)
print('arr_e:--', arr_complex.dtype)

arr_a:-- int64
arr_b:-- float64
arr_c:-- <U9
arr_d:-- <U5
arr_e:-- complex128


In [11]:
# Importance of Data Types:-

#Data types in numpy are crucial for several reasons, primarily related to memory management and performance:

#Memory Management:
#     Size: Different data types have different sizes. Choosing the appropriate data type can significantly reduce memory usage.
#     Efficiency: Using a smaller data type helps in saving memory, which is particularly important for large arrays or when working with limited system resources.

#Performance:
#     Computational Speed: Operations on smaller data types can be faster, e.g, integer arithmetic with int32 can be quicker than with int64 due to lower data size.

###choosing the correct data type for numpy arrays can optimize both memory usage and performance.

In [12]:
#Q5:- Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# An ndarray is a multidimensional, homogeneous array of fixed-size items. It is the core data structure of the numpy library, designed to store and operate
#on large datasets with high performance.

# Key Features of ndarray:-

#(a) Multidimensional: can be 1D (vectors), 2D (matrices), or multi-dimensionals.
#(b) Homogeneous: All elements in an ndarray are of the same data type, which allows for efficient storage and computation.
#(c) Efficient Memory Layout: ndarrays are stored in contiguous blocks of memory, which makes access and manipulation faster compared to Python lists.
#(d) Element-wise Operations: Operations on ndarrays are vectorized, meaning that you can perform operations on entire arrays (e.g., addition, multiplication) 
                              #without the need for explicit loops.
#(e) Broadcasting: it allows operations on arrays of different shapes without explicitly reshaping them, enhancing flexibility and efficiency in array operations.
#(f) Shape : 'shape' attribute returns a tuple of integers representing the size of the array along each dimension. 
#(g) Dimensions: 'ndim' attribute gives the number of dimensions.
#(h) Data Type Control: 'dtype' attribute of an ndarray specifies the data type of its elements (e.g., int32, float64, complex128).

#Performance: numpy operations are implemented in C and optimized for performance. This allows ndarrays to perform large-scale numerical operations 
               #much faster than Python lists.
    

    
#Differences from Standard Python Lists & ndarray:-

#ndarray >> 
#(1) elements must be of the same type, 
#(2) supports multidimensional array(suitable for mathematical operation & data strc.)which ensures efficient computation and storage,
#(3) better performance for large data sets, numerical computations,
#(4) alows fast access and manipulation,
#(5) provides a vast library of mathematical functions (np.mean(),np.average(),np.sum(),np.multiply(),np.dot(),np.substract(),np.devide())
         # that directly on the entire array,

#python lists >>
#(1) elements of different types (e.g., integers, strings, lists),
#(2) Typically used for 1D lists, but can be nested to create multi-dimensional structures, which are less efficient,
#(3) operations are executed in pure python,which is slow & less efficient for large scale computations,
#(4) operations applied element-wise using loops or list comprehension,
#(5) lacks built-in mathematical functions 
   
    

In [13]:
#EXAMPLE:-

#using python list:-

lis = [1, 2, 3, 4, 5]
list_squared = [x**2 for x in lis]      # Element-wise operation using list comprehension

print("Python list:\n", lis)
print("Squared list:\n", list_squared)


Python list:
 [1, 2, 3, 4, 5]
Squared list:
 [1, 4, 9, 16, 25]


In [14]:
#using ndarray:-

import numpy as np
arr=np.array([1,2,3,4,5])
arr_squared=arr**2                       # element-wise operation using ndarray

print('squared numpy:\n', arr_squared)

squared numpy:
 [ 1  4  9 16 25]


In [15]:
# summary:--
#ndarrays provide powerful, efficient, and flexible data structures for numerical computation, contrasting with the more general-purpose 
#and less efficient Python lists.

In [16]:
#Q6:- Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

              
                                     # Here's are some points we have discussed:------
    
#1.Memory Efficiency: numpy arrays use contiguous blocks of memory and fixed data types, leading to more efficient memory use and access.
#2.Performance of Operations: numpy supports vectorized operations and broadcasting, executed with optimized compiled code, leading to faster and 
                              #more efficient computations.
#3.Computational Complexity: numpy operations are optimized for performance with built-in mathematical functions and low-level optimizations.
#4.Speed of Execution: numpy arrays enable faster execution of numerical operations compared to Python lists, which rely on slower element-wise loops and operations.

#(*) Overall, numpy arrays are designed for high-performance numerical computations, making them the preferred choice for large-scale data processing and 
              #scientific computing.


In [17]:
#Q7:-  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.


# vstack():- stacks arrays along the vertical axis (i.e., rows) and requires arrays to have the same number of columns.
#EXAMPLE:
import numpy as np

# Define two 2D arrays
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

# Use vstack to stack them vertically
result = np.vstack((arr1, arr2))

print("Result of vstack:\n", result)

Result of vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
#hstack():- stacks arrays along the horizontal axis (i.e., columns) and requires arrays to have the same number of rows.
#EXAMPLE:
import numpy as np

# Define two 2D arrays
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])

# Use hstack to stack them horizontally
result = np.hstack((arr1, arr2))

print("Result of hstack:\n", result)

Result of hstack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [19]:
#Q8:-  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#fliplr() flips arrays left-to-right (along columns) and is mainly used with 2D arrays.
#EXAMPLE:
import numpy as np

# Define a 2D array
arr_of_2d = np.array([[1,2,3], [4,5,6]])

# Use fliplr to flip horizontally
flipped_lr = np.fliplr(arr_of_2d)

print("Original array:\n", arr_of_2d)
print("Flipped horizontally (fliplr):\n", flipped_lr)


Original array:
 [[1 2 3]
 [4 5 6]]
Flipped horizontally (fliplr):
 [[3 2 1]
 [6 5 4]]


In [20]:
#flipud() flips arrays up-to-down (along rows) and is also mainly used with 2D arrays.
#EXAMPLE:
import numpy as np

# Define a 2D array
arr_of_2d = np.array([[1,2,3],[4,5,6]])

# Use flipud to flip vertically
flipped_ud = np.flipud(arr_of_2d)

print("Original array:\n", arr_of_2d)
print("Flipped vertically (flipud):\n", flipped_ud)


Original array:
 [[1 2 3]
 [4 5 6]]
Flipped vertically (flipud):
 [[4 5 6]
 [1 2 3]]


In [21]:
# EXAMPLE with 3d array
import numpy as np

# Define a 3D array
arr_of_3d = np.array([[[1,2,3], [4,5,6],[7,8,9],[10,11,12]]])

# Flip horizontally
flipped_lr_3d = np.fliplr(arr_of_3d)

# Flip vertically
flipped_ud_3d = np.flipud(arr_of_3d)

print("Original 3D array:\n",arr_of_3d)
print("\nFlipped horizontally (fliplr):\n", flipped_lr_3d)
print("\nFlipped vertically (flipud):\n", flipped_ud_3d)


Original 3D array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

Flipped horizontally (fliplr):
 [[[10 11 12]
  [ 7  8  9]
  [ 4  5  6]
  [ 1  2  3]]]

Flipped vertically (flipud):
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [22]:
#Q9:- Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#array_split() provides flexible splitting options and handles uneven splits gracefully by distributing elements as evenly as possible.
               #This makes it a versatile tool for dividing arrays into manageable pieces, regardless of their size or shape.
    
#EXAMPLE:-
#uneven split in 1D:-

import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
split_indicies=np.array_split(arr, [3,5])        #split the array

print('uneven splits:--\n', split_indicies)


uneven splits:--
 [array([1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


In [23]:
#uneven split in 2D:-

#by rows----

import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
split_rows=np.array_split(arr,2, axis=0)              #split in rows using axis=0

print('uneven split:--\n', split_rows)

uneven split:--
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [24]:
#by column----

import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [6,7,8]])
split_column=np.array_split(arr,2, axis=1)            #split in column using axis=1

print('uneven split:---\n', split_column)

uneven split:---
 [array([[1, 2],
       [4, 5],
       [6, 7]]), array([[3],
       [6],
       [8]])]


In [25]:
# example of even split in 1D:-

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
split_indicies=np.array_split(a,2)      #split evenly

print('even split:\n', split_indicies)

even split:
 [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [26]:
#Q10:- Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
 
# Vectorization: Enables operations on entire arrays at once using optimized, compiled code, leading to faster computations and avoiding explicit loops.
# Broadcasting:  Allows for arithmetic operations on arrays with different shapes by adjusting their shapes virtually, 
                #enabling efficient and straightforward array manipulations.
    
#EXAMPLE OF VECTORIZATION:--

import numpy as np
arr1=np.random.rand(10000000)   # creating two large numpy arrays
arr2=np.random.rand(10000000)

result=arr1+arr2                #vectorisation operation(element-wise addition)

print('adding arrays:\n', result) 

adding arrays:
 [1.63056292 1.00271062 0.73508489 ... 1.87843063 1.34042333 1.05894381]


In [27]:
#EXAMPLE OF BROADCASTING:--

import numpy as np
arr1=np.array([1,2,3])     #creating 1D array
arr2=np.array([[1,2,3],    # creating 2D array
               [4,5,6],
               [7,8,9]])

result=arr1-arr2           #broadcast 1D array to the shape of the 2D aray
print('1D_array:\n', arr1)
print('2D_array:\n', arr2)
print('substract_arrays:\n', result)       #WE use element-wise substraction 

1D_array:
 [1 2 3]
2D_array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
substract_arrays:
 [[ 0  0  0]
 [-3 -3 -3]
 [-6 -6 -6]]


In [28]:
                                                    #PRACTICAL QUESTIONS


#Q1:-  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np
arr=np.random.randint(1,101, size= (3,3))
interchange_arr=arr.T                         #using arr.T   for intercange(transpose) the rows &columns
print('original_arr:\n', arr)
print('transpose_arr:\n', interchange_arr)



original_arr:
 [[78 51 31]
 [72 97 81]
 [48 16 10]]
transpose_arr:
 [[78 72 48]
 [51 97 16]
 [31 81 10]]


In [29]:
#Q2:-     Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


import numpy as np
arr=np.arange(10)
arr1=arr.reshape(2,5)
arr2=arr.reshape(5,2)
print('original_array:\n', arr)
print('reshaped into 2*5:\n', arr1)
print('reshaped into 5*2:\n', arr2)

original_array:
 [0 1 2 3 4 5 6 7 8 9]
reshaped into 2*5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
reshaped into 5*2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
#Q3:-   Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np
arr=np.random.rand(4,4)
array_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)         #using 'np.pad' for zeros of borders all around the elements.
print('4*4 array:\n', arr)
print('border_of_zeros_around_it:\n', array_with_border)


4*4 array:
 [[0.59673662 0.57903149 0.11593303 0.98785268]
 [0.08559456 0.35363368 0.74076582 0.95933417]
 [0.46801025 0.00812743 0.66220737 0.31575182]
 [0.46328663 0.89185585 0.01002133 0.73867577]]
border_of_zeros_around_it:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.59673662 0.57903149 0.11593303 0.98785268 0.        ]
 [0.         0.08559456 0.35363368 0.74076582 0.95933417 0.        ]
 [0.         0.46801025 0.00812743 0.66220737 0.31575182 0.        ]
 [0.         0.46328663 0.89185585 0.01002133 0.73867577 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [31]:
#Q4:-     Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np
arr=np.arange(10,61, 5)       #start>> 10, we use 61 due to np.arange() is exclusive for endpoints, step>> 5(step size b/w values)
arr


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [32]:
#Q5:-   Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

import numpy as np
arr=np.array(['python','numpy','pandas'])
arr1=np.char.upper(arr)
arr2=np.char.lower(arr)
arr3=np.char.title(arr)
arr4=np.char.capitalize(arr)

print('numpy_array_strings:\n', arr)
print('in_uppercase_strings:\n', arr1)
print('in_lowercase_strings:\n', arr2)
print('in-titlecase_strings:\n', arr3)         # titlecase and capitalize we use both,output>> same.
print('in_capitalise_strings:\n', arr4)


numpy_array_strings:
 ['python' 'numpy' 'pandas']
in_uppercase_strings:
 ['PYTHON' 'NUMPY' 'PANDAS']
in_lowercase_strings:
 ['python' 'numpy' 'pandas']
in-titlecase_strings:
 ['Python' 'Numpy' 'Pandas']
in_capitalise_strings:
 ['Python' 'Numpy' 'Pandas']


In [33]:
#Q6:-    Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np
arr=np.array(['hello','saumya','wlcm'])
arr2=np.char.join('  ', arr)
print('original arr:\n', arr)
print('spaced_all_the_words:\n', arr2)

original arr:
 ['hello' 'saumya' 'wlcm']
spaced_all_the_words:
 ['h  e  l  l  o' 's  a  u  m  y  a' 'w  l  c  m']


In [34]:
#Q7:-   Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


import numpy as np
arr1=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr2=np.array([[10,20,30],
              [30,40,50],
              [70,80,90]])
arr3=arr1+arr2
arr4=arr1-arr2
arr5=arr1*arr2
arr6=arr1%arr2

print('1st_2D_array:\n', arr1)
print('2nd_2D_array:\n', arr2)
print('addition_of_two_arrays:\n', arr3)
print('substraction_of_two_arrays:\n', arr4)
print('multiplication_of_two_arrays:\n', arr5)
print('division_of_two_arrays:\n', arr6)

1st_2D_array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd_2D_array:
 [[10 20 30]
 [30 40 50]
 [70 80 90]]
addition_of_two_arrays:
 [[11 22 33]
 [34 45 56]
 [77 88 99]]
substraction_of_two_arrays:
 [[ -9 -18 -27]
 [-26 -35 -44]
 [-63 -72 -81]]
multiplication_of_two_arrays:
 [[ 10  40  90]
 [120 200 300]
 [490 640 810]]
division_of_two_arrays:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
#Q8:-    Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np
arr=np.eye(5)
arr1=np.diag(arr)                    # using np.diag() for extract its diagonal elements in matrix
print('matrix_of_5*5:\n', arr)
print('diagonal elements:\n', arr1)

matrix_of_5*5:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
diagonal elements:
 [1. 1. 1. 1. 1.]


In [36]:
#Q9:- Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

import numpy as np
arr=np.random.randint(0,1001, size=100)
            
#define a function to check if a no. is prime
def is_prime(n):
    'Check if a number is a prime number'
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

prime_numbers = [num for num in arr if is_prime(num)]              #find all prime no. in the array

print('random array:\n', arr)
print('prime no.:\n', prime_numbers)


random array:
 [364 301 648 994  97 378 464 596 133 252 535 727 427 483 891 854 388 316
 387 742 884 526 728  28 711 154  63 725 628 454 239 932 262 206 703 634
 703 767 311 150  33 697 513 398 155 466 701 466 582 663 783 379 999 738
 943 974 501 706 184 243 698  16 250 404 195 305  82   1 844 828 446 885
 800 660 300 619 813 308 839 890 552 711 183 464 501 862 567 885 346 175
 877 550 626  48 633 822  32 626 205 556]
prime no.:
 [np.int32(97), np.int32(727), np.int32(239), np.int32(311), np.int32(701), np.int32(379), np.int32(619), np.int32(839), np.int32(877)]


In [37]:
#Q10:-     Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly average

import numpy as np
daily_temp=np.random.randint(32, 46, size=28)                        # Create a NumPy array representing daily temperatures for a month (30 days)
weekly_temp=daily_temp.reshape(4, 7)                                 # Reshape the array into weeks (assuming 4 weeks of 7 days each)
weekly_average=np.mean(weekly_temp, axis=1)                          # Calculate the weekly averages

print('Daily_temperature_for_Month:----\n',  daily_temp)
print('Weekly_temperature:----\n',  weekly_temp)
print('Weekly_average Temperature:----\n',  weekly_average)

Daily_temperature_for_Month:----
 [44 35 36 44 37 45 37 39 45 39 37 37 38 36 37 41 37 32 44 41 45 38 34 37
 39 33 35 32]
Weekly_temperature:----
 [[44 35 36 44 37 45 37]
 [39 45 39 37 37 38 36]
 [37 41 37 32 44 41 45]
 [38 34 37 39 33 35 32]]
Weekly_average Temperature:----
 [39.71428571 38.71428571 39.57142857 35.42857143]
